version: '3'
services:
  task-management-db:
    image: postgres:latest
    container_name: task-management-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
    volumes:
      - task-management-volume:/var/lib/postgresql/data

volumes:
  task-management-volume: